name: .NET

on:
  push:
    branches:
    - '**'
    paths:
    - 'functions/**'
  pull_request:
    branches: 
    - main
    paths:
    - 'functions/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
